General:
    StartUrl: 'http://example.com'
    DoSleepAfterEachPage: 0
    LogEachPage: false
    LimitUrls: 10 # -1 disable limit

UrlCollector:
    FollowLinks: true
    SaveState: true
    RerunOnFails: true
    LockHost: true

ContentDelivery:
    AllowedContentTypes: ['text/html', 'application/xhtml+xml']

    CurlOptions:
        # pretending to be a google bot
        UserAgent: 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
        ReturnTransfer: true
        FoollowLocation: true
        MaxRedirs: 5
        ConnectTimeout: 20
        Timeout: 120

    Proxy:
        UseProxy: false
        Proxy: "http://example.com/"
        ProxyPort: 8080
        ProxyUserPwd: "[username]:[password]"
        
DataStore:
    database:
        driver: sqlite
        host:
        database: './base.sqlite'
        username:
        password:
        charset: utf8
        collation: utf8_unicode_ci
        prefix:
